import { HttpResponseMovie } from 'src/movies/repositories/interfaces/IMoviesRepository';

export const movies: HttpResponseMovie[] = [
  {
    Title: 'Batman Begins',
    imdbID: 'tt0372784',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOTY4YjI2N2MtYmFlMC00ZjcyLTg3YjEtMDQyM2ZjYzQ5YWFkXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Actors: 'Christian Bale, Michael Caine, Ken Watanabe',
    imdbRating: '8.2',
    Released: '15 Jun 2005',
    Runtime: '140 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Christopher Nolan',
    Response: 'True',
  },
  {
    Title: 'Batman v Superman: Dawn of Justice',
    imdbID: 'tt2975590',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Actors: 'Ben Affleck, Henry Cavill, Amy Adams',
    imdbRating: '6.4',
    Released: '25 Mar 2016',
    Runtime: '151 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Zack Snyder',
    Response: 'True',
  },
  {
    Title: 'The Batman',
    imdbID: 'tt1877830',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg',
    Actors: 'Robert Pattinson, Zoë Kravitz, Jeffrey Wright',
    imdbRating: '7.8',
    Released: '04 Mar 2022',
    Runtime: '176 min',
    Genre: 'Action, Crime, Drama',
    Director: 'Matt Reeves',
    Response: 'True',
  },
  {
    Title: 'Batman',
    imdbID: 'tt0096895',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTYwNjAyODIyMF5BMl5BanBnXkFtZTYwNDMwMDk2._V1_SX300.jpg',
    Actors: 'Michael Keaton, Jack Nicholson, Kim Basinger',
    imdbRating: '7.5',
    Released: '23 Jun 1989',
    Runtime: '126 min',
    Genre: 'Action, Adventure',
    Director: 'Tim Burton',
    Response: 'True',
  },
  {
    Title: 'Batman Returns',
    imdbID: 'tt0103776',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_SX300.jpg',
    Actors: 'Michael Keaton, Danny DeVito, Michelle Pfeiffer',
    imdbRating: '7.1',
    Released: '19 Jun 1992',
    Runtime: '126 min',
    Genre: 'Action, Crime, Fantasy',
    Director: 'Tim Burton',
    Response: 'True',
  },
  {
    Title: 'Batman & Robin',
    imdbID: 'tt0118688',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMGQ5YTM1NmMtYmIxYy00N2VmLWJhZTYtN2EwYTY3MWFhOTczXkEyXkFqcGdeQXVyNTA2NTI0MTY@._V1_SX300.jpg',
    Actors: "Arnold Schwarzenegger, George Clooney, Chris O'Donnell",
    imdbRating: '3.8',
    Released: '20 Jun 1997',
    Runtime: '125 min',
    Genre: 'Action, Sci-Fi',
    Director: 'Joel Schumacher',
    Response: 'True',
  },
  {
    Title: 'Batman Forever',
    imdbID: 'tt0112462',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Actors: 'Val Kilmer, Tommy Lee Jones, Jim Carrey',
    imdbRating: '5.4',
    Released: '16 Jun 1995',
    Runtime: '121 min',
    Genre: 'Action, Adventure',
    Director: 'Joel Schumacher',
    Response: 'True',
  },
  {
    Title: 'The Lego Batman Movie',
    imdbID: 'tt4116284',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg',
    Actors: 'Will Arnett, Michael Cera, Rosario Dawson',
    imdbRating: '7.3',
    Released: '10 Feb 2017',
    Runtime: '104 min',
    Genre: 'Animation, Action, Adventure',
    Director: 'Chris McKay',
    Response: 'True',
  },
  {
    Title: 'The Lego Batman Movie',
    imdbID: 'tt4116284',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_SX300.jpg',
    Actors: 'Will Arnett, Michael Cera, Rosario Dawson',
    imdbRating: '7.3',
    Released: '10 Feb 2017',
    Runtime: '104 min',
    Genre: 'Animation, Action, Adventure',
    Director: 'Chris McKay',
    Response: 'True',
  },
  {
    Title: 'Batman: The Killing Joke',
    imdbID: 'tt4853102',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTdjZTliODYtNWExMi00NjQ1LWIzN2MtN2Q5NTg5NTk3NzliL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Actors: 'Kevin Conroy, Mark Hamill, Tara Strong',
    imdbRating: '6.4',
    Released: '25 Jul 2016',
    Runtime: '76 min',
    Genre: 'Animation, Action, Crime',
    Director: 'Sam Liu',
    Response: 'True',
  },
  {
    Title: 'Batman: Under the Red Hood',
    imdbID: 'tt1569923',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNmY4ZDZjY2UtOWFiYy00MjhjLThmMjctOTQ2NjYxZGRjYmNlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Actors:
      'Bruce Greenwood, Jensen Ackles, John DiMaggio, Neil Patrick Harris',
    imdbRating: '8.1',
    Released: '27 Jul 2010',
    Runtime: '75 min',
    Genre: 'Animation, Action, Crime, Drama, Mystery, Sci-Fi, Thriller',

    Director: 'Brandon Vietti',
    Response: 'True',
  },
  {
    Title: 'Batman: The Dark Knight Returns, Part 1',
    imdbID: 'tt2313197',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMzIxMDkxNDM2M15BMl5BanBnXkFtZTcwMDA5ODY1OQ@@._V1_SX300.jpg',
    Actors: 'Peter Weller, Ariel Winter, David Selby, Wade Williams',
    imdbRating: '8',
    Released: '25 Sep 2012',
    Runtime: '76 min',
    Genre: 'Animation, Action, Crime, Drama, Thriller',
    Director: 'Jay Oliva',
    Response: 'True',
  },
  {
    Title: 'Batman: Mask of the Phantasm',
    imdbID: 'tt0106364',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYTRiMWM3MGItNjAxZC00M2E3LThhODgtM2QwOGNmZGU4OWZhXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg',
    Actors: 'Kevin Conroy, Dana Delany, Hart Bochner',
    imdbRating: '7.8',
    Released: '25 Dec 1993',
    Runtime: '76 min',
    Genre: 'Animation, Action, Adventure',
    Director: 'Eric Radomski, Kevin Altieri, Boyd Kirkland',
    Response: 'True',
  },
  {
    Title: 'Batman: The Dark Knight Returns, Part 2',
    imdbID: 'tt2166834',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYTEzMmE0ZDYtYWNmYi00ZWM4LWJjOTUtYTE0ZmQyYWM3ZjA0XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg',
    Actors: 'Peter Weller, Ariel Winter, Michael Emerson, David Selby',
    imdbRating: '8.4',
    Released: '29 Jan 2013',
    Runtime: '76 min',
    Genre: 'Animation, Action, Crime, Drama, Horror, Sci-Fi, Thriller',
    Director: 'Jay Oliva',
    Response: 'True',
  },
  {
    Title: 'Batman: The Movie',
    imdbID: 'tt0060153',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMmM1OGIzM2UtNThhZS00ZGNlLWI4NzEtZjlhOTNhNmYxZGQ0XkEyXkFqcGdeQXVyNTkxMzEwMzU@._V1_SX300.jpg',
    Actors: 'Adam West, Burt Ward, Lee Meriwether',
    imdbRating: '6.5',
    Released: '30 Jul 1966',
    Runtime: '105 min',
    Genre: 'Action, Adventure, Comedy',
    Director: 'Leslie H. Martinson',
    Response: 'True',
  },
  {
    Title: 'Batman: Year One',
    imdbID: 'tt1672723',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNTJjMmVkZjctNjNjMS00ZmI2LTlmYWEtOWNiYmQxYjY0YWVhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Actors: 'Bryan Cranston, Ben McKenzie, Eliza Dushku, Jon Polito',
    imdbRating: '7.4',
    Released: '18 Oct 2011',
    Runtime: '64 min',
    Genre: 'Animation, Action, Crime, Drama, Thriller',
    Director: 'Sam Liu, Lauren Montgomery',
    Response: 'True',
  },
  {
    Title: 'Batman: Assault on Arkham',
    imdbID: 'tt3139086',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BZDU1ZGRiY2YtYmZjMi00ZDQwLWJjMWMtNzUwNDMwYjQ4ZTVhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Actors: 'Kevin Conroy, Neal McDonough, Hynden Walch, Matthew Gray Gubler',
    imdbRating: '7.5',
    Released: '29 Jul 2014',
    Runtime: '76 min',
    Genre: 'Animation, Action, Adventure, Crime, Sci-Fi, Thriller',
    Director: 'Jay Oliva, Ethan Spaulding',
    Response: 'True',
  },
  {
    Title: 'Batman: Gotham Knight',
    imdbID: 'tt1117563',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BM2I0YTFjOTUtMWYzNC00ZTgyLTk2NWEtMmE3N2VlYjEwN2JlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Actors: 'Kevin Conroy, Jason Marsden, Scott Menville, George Newbern',
    imdbRating: '6.7',
    Released: '08 Jul 2008',
    Runtime: '75 min',
    Genre: 'Animation, Action, Crime, Sci-Fi, Thriller',
    Director:
      'Yasuhiro Aoki, Futoshi Higashide, Toshiyuki Kubooka, Hiroshi Morioka, Jong-Sik Nam, Shôjirô Nishimi, Yûichirô Hayashi(co-Director)',
    Response: 'True',
  },
  {
    Title: 'Son of Batman',
    imdbID: 'tt3139072',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BYjdkZWFhNzctYmNhNy00NGM5LTg0Y2YtZWM4NmU2MWQ3ODVkXkEyXkFqcGdeQXVyNTA0OTU0OTQ@._V1_SX300.jpg',
    Actors: "Jason O'Mara, Stuart Allan, Thomas Gibson, Morena Baccarin",
    imdbRating: '6.7',
    Released: '22 Apr 2014',
    Runtime: '74 min',
    Genre: 'Animation, Action, Adventure, Crime, Drama, Fantasy, Mystery',
    Director: 'Ethan Spaulding',
    Response: 'True',
  },
  {
    Title: 'Superman/Batman: Apocalypse',
    imdbID: 'tt1673430',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMjk3ODhmNjgtZjllOC00ZWZjLTkwYzQtNzc1Y2ZhMjY2ODE0XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Actors: 'Andre Braugher, Kevin Conroy, Tim Daly, Susan Eisenberg',
    imdbRating: '7.1',
    Released: '28 Sep 2010',
    Runtime: '78 min',
    Genre: 'Animation, Action, Adventure, Sci-Fi',
    Director: 'Lauren Montgomery',
    Response: 'True',
  },
];
